project:
  type: website
  output-dir: docs

website:
  title: "Pedagogy Notes"
  navbar:
    left:
      - href: notes/index.qmd
        text: Reading Notes

format:
  html:
    theme: cosmo
    toc: true
