project:
  type: website
  output-dir: docs

website:
  title: "Reading Notes"
  # navbar:
  #   left:
  #     - href: themes.qmd
  #       text: Reading Notes

format:
  html:
    theme: cosmo
    toc: true
